# Generated by Django 3.2.6 on 2021-08-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Оборудования',
                'verbose_name_plural': 'Оборудования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('tech_id', models.IntegerField(verbose_name='Тех. ID')),
                ('invent_id', models.CharField(max_length=20, verbose_name='Инвентарный ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('comment', models.TextField(max_length=200, verbose_name='Комментарий')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invent.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудования',
                'ordering': ['name', 'time_create'],
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200, verbose_name='Комментарий')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed', models.BooleanField(default=False)),
                ('inv_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='invent.inventory', verbose_name='ID оборудования')),
            ],
            options={
                'verbose_name': 'Ремонты',
                'verbose_name_plural': 'Ремонт',
                'ordering': ['created_date', 'inv_id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=40, verbose_name='Кабинет')),
                ('comment', models.TextField(max_length=200, verbose_name='Комментарий')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invent.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Кабинеты',
                'verbose_name_plural': 'Кабинет',
                'ordering': ['department', 'room'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invent.location', verbose_name='Кабинет'),
        ),
    ]
